"""add_oauth_tables

Revision ID: 8eaa0966fb0f
Revises: 0002_cold_storage
Create Date: 2026-01-10 21:14:04.198807
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '8eaa0966fb0f'
down_revision = '0002_cold_storage'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_authorization_codes',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('redirect_uri', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('code_challenge', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.alter_column('concept_aliases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('concepts', 'access_count',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('concepts', 'tier',
               existing_type=postgresql.ENUM('hot', 'cold', name='memory_tier'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('concepts', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('concepts', 'floor_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('concepts', 'purge_eligible',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('documents', 'access_count',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('documents', 'tier',
               existing_type=postgresql.ENUM('hot', 'cold', name='memory_tier'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('documents', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('documents', 'floor_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('documents', 'purge_eligible',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_embeddings_vector_hnsw'), table_name='embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('memory_summaries', 'access_count',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('memory_summaries', 'tier',
               existing_type=postgresql.ENUM('hot', 'cold', name='memory_tier'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('memory_summaries', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('memory_summaries', 'floor_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('memory_summaries', 'purge_eligible',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('observations', 'access_count',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('observations', 'tier',
               existing_type=postgresql.ENUM('hot', 'cold', name='memory_tier'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('observations', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('observations', 'floor_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('observations', 'purge_eligible',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('patterns', 'access_count',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('patterns', 'tier',
               existing_type=postgresql.ENUM('hot', 'cold', name='memory_tier'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('patterns', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('patterns', 'floor_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('patterns', 'purge_eligible',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patterns', 'purge_eligible',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('patterns', 'floor_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'-9999'::double precision"),
               existing_nullable=False)
    op.alter_column('patterns', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('patterns', 'tier',
               existing_type=postgresql.ENUM('hot', 'cold', name='memory_tier'),
               server_default=sa.text("'hot'::memory_tier"),
               existing_nullable=False)
    op.alter_column('patterns', 'access_count',
               existing_type=sa.BIGINT(),
               server_default=sa.text("'0'::bigint"),
               existing_nullable=False)
    op.alter_column('observations', 'purge_eligible',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('observations', 'floor_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'-9999'::double precision"),
               existing_nullable=False)
    op.alter_column('observations', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('observations', 'tier',
               existing_type=postgresql.ENUM('hot', 'cold', name='memory_tier'),
               server_default=sa.text("'hot'::memory_tier"),
               existing_nullable=False)
    op.alter_column('observations', 'access_count',
               existing_type=sa.BIGINT(),
               server_default=sa.text("'0'::bigint"),
               existing_nullable=False)
    op.alter_column('memory_summaries', 'purge_eligible',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('memory_summaries', 'floor_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'-9999'::double precision"),
               existing_nullable=False)
    op.alter_column('memory_summaries', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('memory_summaries', 'tier',
               existing_type=postgresql.ENUM('hot', 'cold', name='memory_tier'),
               server_default=sa.text("'hot'::memory_tier"),
               existing_nullable=False)
    op.alter_column('memory_summaries', 'access_count',
               existing_type=sa.BIGINT(),
               server_default=sa.text("'0'::bigint"),
               existing_nullable=False)
    op.create_index(op.f('ix_embeddings_vector_hnsw'), 'embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('documents', 'purge_eligible',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('documents', 'floor_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'-9999'::double precision"),
               existing_nullable=False)
    op.alter_column('documents', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('documents', 'tier',
               existing_type=postgresql.ENUM('hot', 'cold', name='memory_tier'),
               server_default=sa.text("'hot'::memory_tier"),
               existing_nullable=False)
    op.alter_column('documents', 'access_count',
               existing_type=sa.BIGINT(),
               server_default=sa.text("'0'::bigint"),
               existing_nullable=False)
    op.alter_column('concepts', 'purge_eligible',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('concepts', 'floor_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'-9999'::double precision"),
               existing_nullable=False)
    op.alter_column('concepts', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('concepts', 'tier',
               existing_type=postgresql.ENUM('hot', 'cold', name='memory_tier'),
               server_default=sa.text("'hot'::memory_tier"),
               existing_nullable=False)
    op.alter_column('concepts', 'access_count',
               existing_type=sa.BIGINT(),
               server_default=sa.text("'0'::bigint"),
               existing_nullable=False)
    op.alter_column('concept_aliases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.drop_table('oauth_authorization_codes')
    # ### end Alembic commands ###
